# Generated by Django 5.1.4 on 2024-12-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='銀行名')),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='支店名')),
                ('branch_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='支店コード')),
                ('account_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='預金種別')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='口座番号')),
                ('account_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='名義人')),
                ('account_name_kana', models.CharField(blank=True, max_length=80, null=True, verbose_name='名義人カナ')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会社名')),
                ('short_name', models.CharField(max_length=20, verbose_name='短縮名')),
                ('address1', models.CharField(default='', max_length=150, verbose_name='住所１')),
                ('address2', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='住所２')),
                ('tel', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='電話')),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='Email')),
                ('slug', models.CharField(blank=True, max_length=20, null=True, verbose_name='会社キー')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.bankaccount', verbose_name='銀行名')),
            ],
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='請求日')),
                ('payment_due', models.DateField(blank=True, null=True, verbose_name='請求日')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='該当月')),
                ('action_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='項目')),
                ('action_note', models.CharField(blank=True, max_length=150, null=True, verbose_name='備考')),
                ('invoice_bt', models.IntegerField(default=0, verbose_name='備考')),
                ('invoice_tax', models.IntegerField(default=0, verbose_name='備考')),
                ('invoice_at', models.IntegerField(default=0, verbose_name='備考')),
                ('flag', models.BooleanField(default=False, verbose_name='請求書作成済')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='請求書キー')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.company', verbose_name='取引先')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_item_slug', models.CharField(max_length=30, unique=True, verbose_name='請求書キー')),
                ('invoice_bt_ttl', models.IntegerField(default=0, verbose_name='備考')),
                ('invoice_tax_ttl', models.IntegerField(default=0, verbose_name='備考')),
                ('invoice_at_ttl', models.IntegerField(default=0, verbose_name='備考')),
                ('invoice_slug', models.CharField(blank=True, max_length=30, null=True, verbose_name='請求書番号')),
                ('account_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.accountitem', verbose_name='取引キー')),
            ],
        ),
    ]
