# Generated by Django 5.1.4 on 2024-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='短縮名'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='請求日'),
        ),
    ]
