# Generated by Django 5.1.4 on 2024-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_company_post_code_invoicecode_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='〒'),
        ),
    ]
