# Generated by Django 5.1.4 on 2024-12-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_company_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_at',
            field=models.IntegerField(default=0, verbose_name='税込請求額'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_bt',
            field=models.IntegerField(default=0, verbose_name='請求額'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_tax',
            field=models.IntegerField(default=0, verbose_name='税金'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='支払期日'),
        ),
        migrations.AlterField(
            model_name='invoicecode',
            name='invoice_at_ttl',
            field=models.IntegerField(default=0, verbose_name='税込請求額'),
        ),
        migrations.AlterField(
            model_name='invoicecode',
            name='invoice_bt_ttl',
            field=models.IntegerField(default=0, verbose_name='請求額'),
        ),
        migrations.AlterField(
            model_name='invoicecode',
            name='invoice_tax_ttl',
            field=models.IntegerField(default=0, verbose_name='税金'),
        ),
        migrations.AlterField(
            model_name='invoicecode',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='支払期日'),
        ),
    ]
