# Generated by Django 5.1.4 on 2024-12-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_accountitem_invoice_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='項目名')),
                ('short_name', models.CharField(max_length=20, verbose_name='短縮名')),
                ('slug', models.CharField(blank=True, max_length=20, null=True, verbose_name='項目キー')),
            ],
        ),
    ]
