# Generated by Django 5.1.4 on 2024-12-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountitem',
            name='item_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='invoice.itemcode', verbose_name='項目キー'),
            preserve_default=False,
        ),
    ]
