# Generated by Django 5.1.4 on 2024-12-31 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_accountitem_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='請求日'),
        ),
    ]
