# Generated by Django 5.1.4 on 2024-12-31 03:02

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_accountitem_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_date',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_start_of_next_month, null=True, verbose_name='請求日'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='payment_due',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_end_of_next_month, null=True, verbose_name='支払期日'),
        ),
    ]
