# Generated by Django 5.1.4 on 2024-12-31 03:05

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_accountitem_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='action_date',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_start_of_this_month, null=True, verbose_name='該当月'),
        ),
    ]
