# Generated by Django 5.1.4 on 2024-12-31 03:24

import django.db.models.deletion
import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_accountitem_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='item_code',
            field=models.ForeignKey(default=invoice.models.AccountItem.default_item_code, on_delete=django.db.models.deletion.PROTECT, to='invoice.itemcode', verbose_name='項目キー'),
        ),
    ]
