# Generated by Django 5.1.4 on 2024-12-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_accountitem_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='action_name',
            field=models.CharField(blank=True, default='業務委託費', max_length=150, null=True, verbose_name='項目'),
        ),
    ]
