# Generated by Django 5.1.4 on 2024-12-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_accountitem_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecode',
            name='account_item_slug',
            field=models.CharField(max_length=30, verbose_name='請求書キー'),
        ),
    ]
