# Generated by Django 5.1.4 on 2024-12-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoicecode_account_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecode',
            name='invoice_at_ttl',
        ),
        migrations.RemoveField(
            model_name='invoicecode',
            name='invoice_bt_ttl',
        ),
        migrations.RemoveField(
            model_name='invoicecode',
            name='invoice_slug',
        ),
        migrations.RemoveField(
            model_name='invoicecode',
            name='invoice_tax_ttl',
        ),
        migrations.RemoveField(
            model_name='invoicecode',
            name='payment_due',
        ),
    ]
