# Generated by Django 5.1.4 on 2024-12-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_invoicecode_invoice_at_ttl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecode',
            name='account_item',
        ),
    ]
