# Generated by Django 5.1.4 on 2024-12-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_invoicecode_account_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecode',
            name='account_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.accountitem', verbose_name='取引キー'),
            preserve_default=False,
        ),
    ]
