# Generated by Django 5.1.4 on 2024-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_invoicecode_account_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_at_ttl',
            field=models.IntegerField(default=0, verbose_name='税込請求額'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_bt_ttl',
            field=models.IntegerField(default=0, verbose_name='請求額'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_slug',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='請求書番号'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_tax_ttl',
            field=models.IntegerField(default=0, verbose_name='税金'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='支払期日'),
        ),
    ]
