# Generated by Django 5.1.4 on 2024-12-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_invoicecode_invoice_at_ttl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='register_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='登録番号'),
        ),
    ]
