# Generated by Django 5.1.4 on 2025-01-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_company_register_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountitem',
            name='action_note',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='備考'),
        ),
    ]
