# Generated by Django 5.1.4 on 2025-01-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_alter_accountitem_action_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvdate', models.DateField(default='2024-09-01')),
            ],
        ),
    ]
