# Generated by Django 5.1.4 on 2025-01-02 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_csvdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdate',
            name='csvdate',
            field=models.DateField(default=datetime.date(2024, 9, 1)),
        ),
    ]
