# Generated by Django 5.1.4 on 2025-01-04 13:52

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_csvdate_csvdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_yayoi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='弥生補助科目'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='action_date',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_first_of_last_month, null=True, verbose_name='該当月'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='invoice_date',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_start_of_this_month, null=True, verbose_name='請求日'),
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='payment_due',
            field=models.DateField(blank=True, default=invoice.models.AccountItem.get_end_of_this_month, null=True, verbose_name='支払期日'),
        ),
    ]
