# Generated by Django 5.1.4 on 2025-03-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_company_name_yayoi_alter_accountitem_action_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_at_gttl',
            field=models.IntegerField(default=0, verbose_name='税込請求額'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_bt_ttl_0',
            field=models.IntegerField(default=0, verbose_name='請求額'),
        ),
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_tax_flag',
            field=models.BooleanField(default=True, verbose_name='有税無税'),
        ),
    ]
