# Generated by Django 5.1.4 on 2025-03-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_invoicecode_invoice_at_gttl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecode',
            name='invoice_bt_gttl',
            field=models.IntegerField(default=0, verbose_name='税込請求額'),
        ),
    ]
