# Generated by Django 5.1.4 on 2025-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_invoicecode_invoice_bt_gttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='tax_rate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='税率'),
        ),
    ]
