# Generated by Django 5.1.4 on 2026-09-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0028_require_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address1",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="住所１"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="address2",
            field=models.CharField(
                blank=True, default="", max_length=150, null=True, verbose_name="住所２"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoice.bankaccount",
                verbose_name="銀行名",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="post_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="〒"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="register_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="登録番号"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tel",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="電話"
            ),
        ),
    ]
