# Generated by Django 5.1.4 on 2026-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0031_rename_default_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountitem",
            name="tax_rate",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="税率(%)"),
        ),
    ]
