# Generated by Django 5.1.4 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0033_backfill_accountitem_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicecode",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="送信日時"),
        ),
    ]
