# Generated by Django 5.1.4 on 2026-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0034_invoicecode_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="論理削除日時"
            ),
        ),
        migrations.AddField(
            model_name="invoicecode",
            name="amended",
            field=models.BooleanField(default=False, verbose_name="修正版"),
        ),
    ]
