# Generated by Django 5.1.4 on 2026-09-19 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0036_invoicecode_tax_rounding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="明細ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "追加"),
                            ("update", "変更"),
                            ("void", "論理削除"),
                            ("delete", "削除"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="操作元"
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "invoice_slug",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("after_sent", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="invoice.accountitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="invoice.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "object_id"],
                        name="invoice_cha_organiz_131284_idx",
                    )
                ],
            },
        ),
    ]
